name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4  # 최신 버전 사용 

    - name: Change Directory
      run: cd Liar_Game

    - name: Echo current directory and files
      run: pwd; ls -al

    - name: Build with Gradle Wrapper
      run: ./gradlew build
      working-directory: Liar_Game
      
    - name: Run Tests
      run: ./gradlew test
      working-directory: Liar_Game

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Change directory
      run: cd Liar_Game && ls -al 

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4
      with:
        build-script-name: 'build.gradle'
        gradle-version: '8.11'  # Gradle 버전 지정
